title: Assurance Package Scheme
url: https://govbenefits.gov.sg
favicon: /images/ap_logo.png
colors:
  primary-color: "#6031b6"
  secondary-color: "#4372d6"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: >-
  At Budget 2020, the Government announced a $6 billion Assurance Package (AP)
  for GST to cushion the impact of the planned GST increase for all
  Singaporeans. The AP was enhanced to $6.6 billion at Budget 2022.


  The AP comprises cash payouts for all adult Singaporeans, additional cash for lower-income seniors, additional GST Voucher – U-Save, MediSave top-ups for children and seniors, and Community Development Council (CDC) Vouchers for Singaporean households. In addition, the Government will provide a top up to the Citizens’ Consultative Committee (CCC) ComCare Fund and grants to self-help groups.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://cpf-govbenefits-staging.netlify.app
prod: https://cpf-govbenefits-prod.netlify.app
shareicon: /images/ap_logo.png
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
